# 车次列表页初始需求文档
# 这是提供给 UI Analyzer Agent 的输入文档
# Agent 会自动获取截图、图片资源和交互场景截图

# ⚠️ 使用说明：
# 1. 如果某个组件需要交互场景截图，请在 description 中添加 "**交互场景截图**:" 字段
# 2. Agent 会按照 steps 中定义的步骤自动执行交互并截图
# 3. 支持的 action 类型: type, click, wait, wait_for_element, screenshot, evaluate 等

- id: REQ-TRAIN-LIST-PAGE
  name: 车次列表页
  description: |
    显示查询结果的车次列表页面，用户可以筛选和选择车次。
    
    **网站地址**: http://localhost:5174/trains (需要先从首页查询后跳转)
    **页面宽度参考**: 1920px
    
    **访问方式**:
    1. 先访问首页 http://localhost:5174/trains
    2. 填写查询条件（如：北京 -> 上海，明天日期）
    3. 点击查询按钮
    4. 自动跳转到车次列表页
    
    **需要的图片资源**:
    - Logo（顶部导航）
    - 导航菜单图标（如有）
    - 筛选图标（如有）
    - 无结果提示图片（如有）
    
    **主要功能**：
    - 显示查询条件摘要
    - 支持修改查询条件（出发地、目的地、日期）
    - 显示车次列表（车次号、出发/到达时间、历时、余票等）
    - 支持多维度筛选（车次类型、出发时间段、车站、席别等）
    - 支持排序（出发时间、历时、票价等）
    - 点击车次可以预订
  
  dependencies: []
  scenarios: []
  
  children:
    - id: REQ-TRAIN-LIST-TOP-NAV
      name: 顶部导航栏
      description: |
        页面顶部导航栏（与首页共用）。
        
        **需要截图**: 是
        **组件定位**: 页面最上方，横向占据整个页面宽度
        **定位提示**: header, nav, .header, [role="banner"]
        
        **功能要求**：
        - 显示12306品牌Logo
        - 显示主导航菜单
        - 显示用户登录状态
        - Logo点击返回首页
      
      dependencies: []
      scenarios: []
      children: []
    
    - id: REQ-TRAIN-SEARCH-BAR
      name: 查询条件栏
      description: |
        显示当前查询条件，支持快速修改。
        
        **需要截图**: 是
        **组件定位**: 页面顶部导航下方，横向占据页面宽度，高度约60-80px
        **定位提示**: .search-bar, .query-bar, .ticket-search, [class*="search"]
        
        **功能要求**：
        - 显示当前出发地、目的地、日期
        - 支持点击修改出发地、目的地、日期
        - 提供出发地和目的地互换按钮
        - 提供"重新查询"或"查询"按钮
        - 显示前一天/后一天日期切换按钮
        
        **交互场景截图**:
          - name: "修改查询条件"
            description: "测试点击出发地修改查询条件"
            steps:
              - action: click
                target: "出发地区域"
                target_hint: ".from-station, [class*='from'], input[placeholder*='出发']"
              - action: wait
                duration: 1
              - action: screenshot
                filename: "查询条件栏-修改出发地.png"
      
      dependencies: []
      
      scenarios:
        # 4.3.1 用户未输入出发地或到达地或出发日期时，系统自动填充默认值
        - name: 用户未输入出发地自动填充默认值
          given: 用户在车票查询页面
          when: 用户未在车次搜索和查询区域的搜索栏中输入出发地或还未进行输入出发地操作
          then: 系统在"出发地"输入框填入默认状态，即"请选择城市"
          
        - name: 用户未输入到达地自动填充默认值
          given: 用户在车票查询页面
          when: 用户未在车次搜索和查询区域的搜索栏中输入到达地或还未进行输入到达地操作
          then: 系统在"到达地"输入框填入默认状态，即"请选择城市"
          
        - name: 用户未输入出发日期自动填充当前日期
          given: 用户在车票查询页面
          when: 用户未在车次搜索和查询区域的搜索栏中输入出发日期或还未进行输入出发日期操作
          then: 系统在"出发日期"输入框填入默认状态，即当前日期
          
        # 4.3.2 用户未输入出发地或到达地，点击"查询"按钮
        - name: 用户未输入出发地点击查询
          given: 用户在车票查询页面，用户在车次搜索和查询区域的搜索栏中未输入出发地
          when: 用户点击"查询"按钮
          then: "出发地"输入框下方出现错误提示"请选择出发城市"，文字颜色#d32f2f（红色），字体大小12px，绝对定位在输入框下方，上边距2px，"出发地"输入框边框变为#d32f2f（红色）
          
        - name: 用户未输入到达地点击查询
          given: 用户在车票查询页面，用户在车次搜索和查询区域的搜索栏中输入了出发地但未输入到达地
          when: 用户点击"查询"按钮
          then: "到达地"输入框下方出现错误提示"请选择到达城市"，文字颜色#d32f2f（红色），字体大小12px，绝对定位在输入框下方，上边距2px，"到达地"输入框边框变为#d32f2f（红色）
          
        # 4.3.3 校验用户输入的出发地是否合法
        - name: 出发地不在数据库城市列表中
          given: 用户在车次搜索和查询区域的出发地输入框中输入了一个不在数据库中的城市作为出发地
          when: 用户在车次搜索和查询区域中点击"查询"
          then: 查询按钮上方出现系统提示"无法匹配该出发城市"，文字颜色#d32f2f（红色），字体大小13px，内边距8px 20px，背景#ffebee（浅红色），圆角4px，上边距10px，系统在出发地输入框下拉条目中推荐具有一定相似度的数据库中的城市，用户可以点击推荐城市，将其填充到出发地输入框中
          
        # 4.3.4 校验用户输入的到达地是否合法
        - name: 到达地不在数据库城市列表中
          given: 用户在车次搜索和查询区域的到达地输入框中输入了一个不在数据库的城市作为到达地
          when: 用户在车次搜索和查询区域中点击"查询"
          then: 查询按钮上方出现系统提示"无法匹配该到达城市"，文字颜色#d32f2f（红色），字体大小13px，内边距8px 20px，背景#ffebee（浅红色），圆角4px，上边距10px，系统在到达地输入框下拉条目中推荐具有一定相似度的数据库中的城市，用户可以点击推荐城市，将其填充到到达地输入框中
          
        # 4.3.5 合法出发地推荐
        - name: 合法出发地推荐
          given: 用户在车票查询页面
          when: 用户在车次搜索和查询区域中点击出发地输入框
          then: 系统在出发地输入框下拉条目中显示数据库存储的所有站点，用户可以点击推荐城市，将其填充到出发地输入框中
          
        # 4.3.6 合法到达地推荐
        - name: 合法到达地推荐
          given: 用户在车票查询页面
          when: 用户在车次搜索和查询区域中点击到达地输入框
          then: 系统在到达地输入框下拉条目中显示数据库存储的所有站点，用户可以点击推荐城市，将其填充到到达地输入框中
          
        # 4.3.7 合法出发日期推荐
        - name: 合法出发日期推荐
          given: 用户在车票查询页面
          when: 用户在车次搜索和查询区域中点击出发日期选择框
          then: 系统在出发日期选择框下拉条目中显示日历，已放票的日期显示为黑色，不能选择已过期或未开票的日期显示为灰色，用户如果点击已放票的日期，将其填充到出发日期选择框中，用户如果点击已过期或未放票的日期，页面保持不变，无法将该日期填充到出发日期选择框内
          
        # 4.3.8 用户成功查询且系统响应
        - name: 查询成功且系统响应
          given: 用户在车票查询页面的车次搜索和查询区域中输入了正确的出发地、到达地、出发日期
          when: 用户点击"查询"按钮
          then: 系统在100毫秒内在车票查询页面的车次列表区域显示符合用户选择的出发地、到达地、出发日期且是"GC-高铁/城际"，"D-动车"的所有车次信息列表
          
        # 4.3.9 用户成功查询但系统未响应
        - name: 查询失败系统未响应
          given: 用户在车票查询页面的车次搜索和查询区域中输入了正确的出发地、到达地、出发日期
          when: 用户点击"查询"按钮
          then: 系统未在100毫秒内显示符合用户选择的出发地、到达地、出发日期且是"GC-高铁/城际"，"D-动车"的所有车次信息列表，查询按钮上方出现系统提示"查询失败，请稍后重试"，文字颜色#d32f2f（红色），字体大小13px，内边距8px 20px，背景#ffebee（浅红色），圆角4px，上边距10px
      
      children: []
    
    - id: REQ-TRAIN-FILTER
      name: 筛选条件区域
      description: |
        车次筛选条件，支持多维度筛选。
        
        **需要截图**: 是
        **组件定位**: 位于车次列表上方或左侧，通常为多行横向布局
        **定位提示**: .filter, .screen, [class*="filter"]
        
        **功能要求**：
        - 车次类型筛选（高铁/动车、普通列车、D字头、G字头、K字头等）
        - 出发时间段筛选（00:00-06:00、06:00-12:00、12:00-18:00、18:00-24:00）
        - 出发车站筛选（如有多个车站）
        - 到达车站筛选（如有多个车站）
        - 席别筛选（商务座、一等座、二等座、硬座、硬卧、软卧等）
        - 是否只看有票
        - 支持多选和取消选择
        - 显示筛选结果数量
        
        **交互场景截图**:
          - name: "车次类型筛选"
            description: "测试点击高铁/动车筛选"
            steps:
              - action: click
                target: "高铁/动车筛选按钮"
                target_hint: "button:has-text('高铁'), .filter-item:has-text('高铁'), [data-type='高铁']"
              - action: wait
                duration: 1
              - action: screenshot
                filename: "筛选条件-高铁筛选激活.png"
                
          - name: "出发时间段筛选"
            description: "测试点击早上时间段筛选"
            steps:
              - action: click
                target: "早上时间段筛选按钮"
                target_hint: "button:has-text('06:00-12:00'), [data-time='morning']"
              - action: wait
                duration: 1
              - action: screenshot
                filename: "筛选条件-时间段筛选激活.png"
      
      dependencies: []
      
      scenarios:
        # 4.5.1 用户通过勾选复选框筛选车次
        - name: 用户筛选某个车次类型
          given: 用户在车票查询页面，车次列表区域已显示
          when: 用户在车次类型筛选栏中勾选某个车次类型复选框
          then: 车次列表区域的车次信息自动更新，仅显示符合该选项的车次，不检查相应车次是否有余票
          
        - name: 用户筛选某个出发站
          given: 用户在车票查询页面，车次列表区域已显示
          when: 用户在出发车站筛选栏中勾选某个出发站复选框
          then: 车次列表区域的车次信息自动更新，仅显示从该出发站出发的车次
          
        - name: 用户筛选某个到达站
          given: 用户在车票查询页面，车次列表区域已显示
          when: 用户在到达车站筛选栏中勾选某个到达站复选框
          then: 车次列表区域的车次信息自动更新，仅显示到达该到达站的车次
          
        - name: 用户筛选某个席别座位
          given: 用户在车票查询页面，车次列表区域已显示
          when: 用户在某个筛选栏（如"车次席别"筛选栏）中勾选某个席别座位复选框
          then: 车次列表区域的车次信息自动更新，仅显示符合该选项的车次，不检查相应车次是否有余票
          
        - name: 用户在同一筛选栏目勾选多个选项
          given: 用户在车票查询页面，车次列表区域已显示
          when: 用户在某个筛选栏（如"车次类型"筛选栏）中勾选多于一个复选框
          then: 车次列表区域的车次信息自动更新，仅显示符合该筛选栏所勾选的选项的车次，不检查相应车次是否有余票（如用户勾选了"GC-高铁/城际"和"D-动车"，则仅显示"G"或"C"开头的车次或"D"字头的车次）
          
        - name: 用户在不同筛选栏目勾选多个选项
          given: 用户在车票查询页面，车次列表区域已显示
          when: 用户在"车次类型"、"出发车站"、"到达车站"、"车次席别"筛选栏中勾选多于一个复选框（如勾选"GC-高铁/城际"、"D-动车"、"出发站A"、"到达站B"、"一等座"）
          then: 车次列表区域的车次信息自动更新，仅显示符合所勾选的"车次类型"、"出发车站"、"到达车站"、"车次席别"的车次，不检查相应车次是否有余票（如用户勾选了"GC-高铁/城际"、"D-动车"、"出发站A"、"到达站B"、"一等座"，则仅显示"G"或"C"开头的车次或"D"字头的车次，从"出发站A"出发到达"到达站B"，有"一等座"的车次）
          
        - name: 用户取消筛选条件
          given: 用户在车次信息筛选区域已勾选"GC-高铁/城际"复选框，车次列表区域的车次信息已筛选
          when: 用户再次点击并取消勾选"GC-高铁/城际"复选框
          then: 车次信息列表自动更新，移除"车次类型"的筛选限制，显示所有符合其他筛选条件的车次
          
        - name: 默认筛选栏初始化
          given: 用户在车票查询页面
          when: 车次信息列表未显示
          then: 系统默认初始化"车次类型"筛选栏选项为"GC-高铁/城际"、"D-动车"，"出发车站"、"到达车站"、"车次席别"筛选栏为空
          
        - name: 自动补全筛选选项栏
          given: 用户在车票查询页面
          when: 车次列表区域的车次信息已显示
          then: 系统自动补全"出发车站"的选项为车次列表区域所有已显示车次的出发站，"到达车站"的选项为所有车次列表区域已显示车次的到达站，系统自动补全"车次席别"的选项为所有车次列表区域已显示车次的席别座位类型
      
      children: []
    
    - id: REQ-TRAIN-LIST
      name: 车次列表
      description: |
        显示符合条件的车次列表，每行是一个车次。
        
        **需要截图**: 是
        **组件定位**: 页面主内容区域，占据大部分空间
        **定位提示**: .train-list, .ticket-list, table, [class*="list"]
        
        **功能要求**：
        - 显示车次号（如G1、D101等）
        - 显示出发车站、到达车站、出发时间、到达时间
        - 显示历时（如2小时15分）
        - 显示各席别余票数量（商务座、一等座、二等座等）
        - 余票不足时显示"无"或"--"
        - 提供"预订"按钮（每行一个）
        - 无票时"预订"按钮置灰不可点击
        - 支持点击车次号查看详情（停靠站信息）
        - 支持悬停高亮当前行
        
        **交互场景截图**:
          - name: "车次列表正常显示"
            description: "获取车次列表的正常显示状态"
            steps:
              - action: wait
                duration: 2
              - action: screenshot
                filename: "车次列表-正常显示.png"
                
          - name: "悬停车次行"
            description: "测试鼠标悬停在某一车次上的效果"
            steps:
              - action: evaluate
                script: |
                  const firstRow = document.querySelector('.train-list tr:first-child, .ticket-item:first-child');
                  if (firstRow) {
                    firstRow.dispatchEvent(new MouseEvent('mouseenter', { bubbles: true }));
                  }
              - action: wait
                duration: 0.5
              - action: screenshot
                filename: "车次列表-悬停高亮.png"
                
          - name: "点击车次号查看详情"
            description: "测试点击车次号展开停靠站信息"
            steps:
              - action: click
                target: "第一个车次号"
                target_hint: ".train-number:first-child, a:has-text('G'), a:has-text('D')"
              - action: wait
                duration: 1
              - action: screenshot
                filename: "车次列表-车次详情展开.png"
      
      dependencies: []
      
      scenarios:
        # 4.2.1 首页通过点击"车票"快捷页面入口进入车票查询页面
        - name: 从首页进入车票查询页面采用默认搜索栏内容
          given: 用户在首页通过点击"车票"快捷页面入口
          when: 车票查询页面成功加载
          then: 车票查询页面的车次列表区域为空，且车次搜索和查询区域搜索框中均为默认状态，车票查询页面的车次信息筛选区域筛选栏中所有选项均为默认状态，即未被勾选
          
        # 4.2.2 用户在首页/查询页中输入出发站、到达站、出发日期信息后跳转
        - name: 从首页查询后跳转车票查询页面
          given: 用户在首页/查询页中输入出发站、到达站、出发日期信息
          when: 用户点击"查询"按钮
          then: 跳转到车票查询页面，车票查询页面的车次列表区域会展示符合条件的车次列表，并且自动将用户输入的出发站、到达站、出发日期填充到搜索框中
          
        - name: 从首页勾选高铁动车选项后跳转
          given: 用户在首页/查询页中输入出发站、到达站、出发日期信息后，点击"查询"按钮，即可跳转到车票查询页面，用户在首页/查询页中勾选了"GC-高铁/城际"选项
          when: 车票查询页面成功加载
          then: 车票查询页面会自动勾选车次信息筛选区域筛选框中的"GC-高铁/城际"和"D-动车"选项，车次列表区域仅展示符合条件的高铁和动车车次
          
        # 4.5.2 系统根据余票状态显示不同信息
        - name: 系统显示具体余票数量（少于20张）
          given: 用户在车票查询页面，某车次已显示在车次列表区域中
          when: 系统从数据库中加载该车次的各种席位的余票信息，该车次某种席位余票数量少于20张
          then: 该单元格直接显示剩余票数，字体大小13px，字体加粗（font-weight:800），颜色#000000（黑色），内边距2px 0
          
        - name: 系统显示"有票"（余票充足）
          given: 用户在车票查询页面，某车次已显示在车次信息列表中
          when: 系统加载该车次的各种席位的余票信息，该车次某种席位余票数量大于等于20张
          then: 该单元格显示"有"，字体大小13px，字体加粗（font-weight:600），颜色#52c41a（绿色），内边距2px 0
          
        - name: 系统显示"无票"（已售罄）
          given: 用户在车票查询页面，某车次已显示在车次信息列表中
          when: 系统加载该车次的各种席位的余票信息，该车次某种席位余票数量为0张
          then: 该单元格显示"无"，字体大小13px，字体加粗（font-weight:500），颜色#999999（灰色），内边距2px 0
          
        - name: 系统显示"--"（该车次无该席别票）
          given: 用户在车票查询页面，已根据筛选条件显示了部分车次
          when: 系统加载这些车次的各种席位的信息，某车次没有车次列表中对应席位类别（如"GZ-高铁/城际"车次没有"硬卧"席位）
          then: 该车次在车次列表区域对应单元格显示"--"，字体大小13px，字体加粗（font-weight:500），颜色#999999（灰色），内边距2px 0
          
        - name: 系统更新余票状态
          given: 用户在车票查询页面，某车次已显示在车次列表区域中，且已加载该车次的各种席位的余票信息
          when: 用户刷新界面
          then: 系统根据最新的余票信息，更新车次列表区域中对应单元格的显示内容
          
        - name: 用户超过五分钟未刷新界面
          given: 用户在车票查询页面，某车次已显示在车次列表区域中，且已加载该车次的各种席位的余票信息
          when: 用户未刷新界面，超过五分钟
          then: 系统出现弹窗提示"页面内容已过期，请重新查询！"
          
        # 4.4.1 用户在网络异常状态下尝试预定
        - name: 用户网络异常下点击"预订"
          given: 用户在车票查询页面，车次列表区域已显示，用户网络异常
          when: 用户点击某个可以预定的车次的"预定"按钮
          then: 系统弹出提示"网络忙，请稍后重试"，弹窗包含"确认"按钮，点击可以关闭弹窗并退回车票查询页面
          
        # 4.4.1 用户未登录状态下点击"预订"
        - name: 用户未登录时点击"预订"按钮
          given: 用户未登录，用户在车票查询页面，用户网络正常
          when: 用户点击任一车次后的"预订"按钮
          then: 页面中出现弹窗提示"请先登录！"，弹窗包含"确认"按钮允许用户点击并跳转至登录页面，若用户点击"取消"按钮，则弹窗关闭，用户继续在车票查询页面操作
          
        # 4.4.2 用户已登录状态下点击"预订"
        - name: 某车次车票已售罄
          given: 用户在车票查询页面，车次列表已显示
          when: 某车次所有席别状态均显示为"无"
          then: "预定"按钮显示为灰色，用户无法点击该按钮
          
        - name: 用户点击"预订"时车票恰好售罄（发生并发冲突）
          given: 用户已登录，用户在车票查询页面，用户所选车次的"预订"按钮处于可点击状态，用户网络正常
          when: 用户点击该车次后的"预订"按钮，但服务器端校验发现所有席别均已售罄
          then: 系统弹出提示"手慢了，该车次车票已售罄！"，弹窗包含"确认"按钮允许用户点击并返回车票查询页面，页面停留在车票查询页面，并刷新当前车次列表
          
        - name: 用户点击"预订"时距离发车时间不足3小时
          given: 用户已登录，用户在车票查询页面，用户所选车次距离发车时间不足3小时，用户网络正常
          when: 用户点击该车次后的"预订"按钮
          then: 页面中央出现弹窗提示"您选择的列车距开车时间很近了，进站约需20分钟，请确保有足够的时间办理安全检查、实名制验证及检票等手续，以免耽误您的旅行。"，提示弹窗包含"确认"和"取消"按钮，点击"确认"按钮关闭弹窗并在100ms之内加载购票页面，点击"取消"按钮关闭弹窗，用户继续在车票查询页面操作
          
        - name: 用户点击有余票车次的"预订"按钮
          given: 用户已登录，用户在车票查询页面，用户所选车次有余票（席别状态显示为具体数字或"有"），用户网络正常
          when: 用户点击该车次后的"预订"按钮
          then: 页面在100ms之内跳转到该车次的购票页面
          
        - name: 用户点击"预定"按钮时距离车次列表上次刷新时间超过5分钟
          given: 用户已登录，用户在车票查询页面，当前时间距离车次列表上次刷新时间超过5分钟
          when: 用户点击某可以被预定的车次后的"预订"按钮
          then: 页面中央出现弹窗提示"页面内容已过期，请重新查询！"，提示弹窗包含"确认"和"取消"按钮，点击"确认"按钮重新加载并刷新当前车次列表，点击"取消"按钮关闭弹窗，车次列表保持不变并且刷新时间仍然为上次的刷新时间
          
        # 通用场景
        - name: 无符合条件的车次
          given: 用户筛选条件过严或查询的线路当天无车次
          when: 页面加载完成
          then: 车次列表区域为空白并出现提示"暂无符合条件的车次"，内边距60px 20px，文字颜色#999999（灰色），图标字体大小48px，文字字体大小16px，颜色#666666（深灰色）
          
        - name: 车次加载中
          given: 用户刚进入车次列表页，数据还在加载
          when: 页面正在加载
          then: 显示加载动画或"正在查询，请稍候..."提示
      
      children: []
    
    - id: REQ-TRAIN-LIST-BOTTOM
      name: 底部导航
      description: |
        页面底部的友情链接和版权信息区域（与首页共用）。
        
        **需要截图**: 是
        **组件定位**: 页面最底部
        **定位提示**: footer, [role="contentinfo"]
        
        **功能要求**：
        - 显示友情链接
        - 显示二维码
        - 显示版权和备案信息
      
      dependencies: []
      scenarios: []
      children: []